title: Luiz Venturote
description: Magento developer

gems: [jekyll-paginate]

url: http://luizventurote.github.io/index.html
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: mailto:luizventurote@gmail.com

social:
   github: luizventurote
   twitter:
   facebook: luizventurote
   linkedin: https://br.linkedin.com/in/luizventurote
   email: luizventurote@gmail.com

google_analytics: "UA-58263416-1"
