title: Luiz Venturote
description: Magento developer

url: http://luizventurote.github.io/index.html
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: luizventurote
   twitter:
   facebook: luizventurote
   email: luizventurote@hotmail.com

google_analytics: "UA-58263416-1"
